
version: '2'

services:

  yb-master-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-0
      hostname: yb-master-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=local
                --placement_region=local
                --placement_zone=local
                --rpc_bind_addresses=yb-master-0:7100
                --master_addresses=yb-master-0:7100
                --replication_factor=1
                "
      ports:
      - "7000:7000"

  yb-tserver-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-0
      hostname: yb-tserver-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=local 
                --placement_region=local 
                --placement_zone=local 
                --placement_uuid=rw
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-0:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --replication_factor=1 
                "
      ports:
      - "9000:9000"
      - "5433:5433"
      depends_on:
      - yb-master-0

  yb-tserver-n:
      image: yugabytedb/yugabyte:latest
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=local 
                --placement_region=local 
                --placement_zone=local 
                --placement_uuid=rw
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --tserver_master_addrs=yb-master-0:7100 
                --replication_factor=1 
                "
      depends_on:
      - yb-master-0
      deploy:
          replicas: 0


