
version: '2'

services:

  yb-demo:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh",""]
      deploy:
          replicas: 3
          restart_policy:
             condition: on-failure
      depends_on:
      - yb-tserver-2

  yb-demo-init:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","init"]
      depends_on:
      - yb-tserver-2


  yb-master-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-0
      hostname: yb-master-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud1
                --placement_region=region1
                --placement_zone=zone1
                --rpc_bind_addresses=yb-master-0:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                "
      ports:
      - "7000:7000"


  yb-tserver-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-0
      hostname: yb-tserver-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud1 
                --placement_region=region1 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-0:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9000:9000"
      - "5433:5433"
      depends_on:
      - yb-master-2


  yb-master-1:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-1
      hostname: yb-master-1
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud2
                --placement_region=region1
                --placement_zone=zone1
                --rpc_bind_addresses=yb-master-1:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                "
      ports:
      - "7001:7000"
      depends_on:
      - yb-master-0


  yb-tserver-1:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-1
      hostname: yb-tserver-1
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud2 
                --placement_region=region1 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-1:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9001:9000"
      - "5434:5433"
      depends_on:
      - yb-master-2


  yb-master-2:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-2
      hostname: yb-master-2
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud1
                --placement_region=region2
                --placement_zone=zone1
                --rpc_bind_addresses=yb-master-2:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                "
      ports:
      - "7002:7000"
      depends_on:
      - yb-master-1


  yb-tserver-2:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-2
      hostname: yb-tserver-2
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud1 
                --placement_region=region2 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-2:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9002:9000"
      - "5435:5433"
      depends_on:
      - yb-master-2


  yb-tserver-3:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-3
      hostname: yb-tserver-3
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud2 
                --placement_region=region2 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-3:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9003:9000"
      - "5436:5433"
      depends_on:
      - yb-master-2


  yb-tserver-4:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-4
      hostname: yb-tserver-4
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud1 
                --placement_region=region1 
                --placement_zone=zone2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-4:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9004:9000"
      - "5437:5433"
      depends_on:
      - yb-master-2


  yb-tserver-5:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-5
      hostname: yb-tserver-5
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud2 
                --placement_region=region1 
                --placement_zone=zone2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-5:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9005:9000"
      - "5438:5433"
      depends_on:
      - yb-master-2


  yb-tserver-6:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-6
      hostname: yb-tserver-6
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud1 
                --placement_region=region2 
                --placement_zone=zone2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-6:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9006:9000"
      - "5439:5433"
      depends_on:
      - yb-master-2


  yb-tserver-7:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-7
      hostname: yb-tserver-7
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud2 
                --placement_region=region2 
                --placement_zone=zone2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-7:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                
                "
      ports:
      - "9007:9000"
      - "5440:5433"
      depends_on:
      - yb-master-2

