version: '3.8'

services:
  yb-master-0:
    image: yugabytedb/yugabyte:2.17.2.0-b216
    container_name: yb-master-0
    hostname: yb-master-0
    command: bash -c " \
      rm -rf /tmp/.yb* ; \
      /home/yugabyte/bin/yb-master --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20 \
      --fs_data_dirs=/home/yugabyte/data \
      --rpc_bind_addresses=yb-master-0:7100 \
      --master_addresses=yb-master-0:7100 \
      --replication_factor=3 \
      --rpc_connection_timeout_ms=15000"
    ports:
      - "7001:7000"

  yb-tserver-0:
    image: yugabytedb/yugabyte:2.17.2.0-b216
    container_name: yb-tserver-0
    hostname: yb-tserver-0
    volumes:
      - ./auth_service/:/app
    command: bash -c " \
      rm -rf /tmp/.yb* ; \
      /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20 \
      --placement_cloud=cloud \
      --placement_region=region \
      --placement_zone=zone1 \
      --enable_ysql=true \
      --fs_data_dirs=/home/yugabyte/data \
      --rpc_bind_addresses=yb-tserver-0:9100 \
      --tserver_master_addrs=yb-master-0:7100 \
      --ysql_num_shards_per_tserver=2 \
      --rpc_connection_timeout_ms=15000"
    ports:
      - "9000:9000"
      - "5433:5433"
    depends_on:
      - yb-master-0
