
version: '2'

services:

# demos with connect / read / write workloads

  yb-demo-connect:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","connect","9"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-read:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","read","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-write:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","insert","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

# table create and other initialization for demos

  yb-demo-init:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","init"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-metrics:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","ybwr"]
      deploy:
          restart_policy:
             condition: on-failure

  sqlpad:
      image: sqlpad/sqlpad:5
      hostname: 'sqlpad'
      ports:
          - '3000:3000'
      depends_on:
          - yb-tserver-1
      volumes:
          - /var/tmp/sqlpad:/var/lib/sqlpad
      environment:
          SQLPAD_AUTH_DISABLED: true
          SQLPAD_ADMIN: 'admin'
          SQLPAD_ADMIN_PASSWORD: 'admin'
          SQLPAD_APP_LOG_LEVEL: debug
          SQLPAD_WEB_LOG_LEVEL: warn
          SQLPAD_SEED_DATA_PATH: /etc/sqlpad/seed-data
          SQLPAD_CONNECTIONS__yb-tserver-1__name: yb-tserver-1
          SQLPAD_CONNECTIONS__yb-tserver-1__driver: postgres
          SQLPAD_CONNECTIONS__yb-tserver-1__host: yb-tserver-1
          SQLPAD_CONNECTIONS__yb-tserver-1__port: 5433
          SQLPAD_CONNECTIONS__yb-tserver-1__database: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-1__username: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-1__password: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-1__multiStatementTransactionEnabled: 'true'
          SQLPAD_CONNECTIONS__yb-tserver-1__idleTimeoutSeconds: 86400
          SQLPAD_CONNECTIONS__yb-tserver-2__name: yb-tserver-2
          SQLPAD_CONNECTIONS__yb-tserver-2__driver: postgres
          SQLPAD_CONNECTIONS__yb-tserver-2__host: yb-tserver-2
          SQLPAD_CONNECTIONS__yb-tserver-2__port: 5433
          SQLPAD_CONNECTIONS__yb-tserver-2__database: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-2__username: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-2__password: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-2__multiStatementTransactionEnabled: 'true'
          SQLPAD_CONNECTIONS__yb-tserver-2__idleTimeoutSeconds: 86400
          SQLPAD_CONNECTIONS__yb-tserver-3__name: yb-tserver-3
          SQLPAD_CONNECTIONS__yb-tserver-3__driver: postgres
          SQLPAD_CONNECTIONS__yb-tserver-3__host: yb-tserver-3
          SQLPAD_CONNECTIONS__yb-tserver-3__port: 5433
          SQLPAD_CONNECTIONS__yb-tserver-3__database: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-3__username: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-3__password: yugabyte
          SQLPAD_CONNECTIONS__yb-tserver-3__multiStatementTransactionEnabled: 'true'
          SQLPAD_CONNECTIONS__yb-tserver-3__idleTimeoutSeconds: 86400

# yb-master and yb-tservers


  yb-master-0:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      container_name: yb-master-0
      hostname: yb-master-0.zone1.region.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud
                --placement_region=region
                --placement_zone=zone1
                --rpc_bind_addresses=yb-master-0.zone1.region.cloud:7100
                --master_addresses=yb-master-0:7100
                --replication_factor=1
                --rpc_connection_timeout_ms=15000
                "
      ports:
      - "7000:7000"


  yb-tserver-0:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      container_name: yb-tserver-0
      hostname: yb-tserver-0.zone1.region.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-0.zone1.region.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9000:9000"
      - "5433:5433"
      depends_on:
      - yb-master-0

# adding a template to add more replicas

  yb-tserver-n:
      image: yugabytedb/yugabyte:2.15.3.0-b231
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      deploy:
          replicas: 0
      depends_on:
      - yb-master-0
