name: yb-lab

# The build section defines how to build the images of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#build
build:

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_YB-DEMO-CONNECT_REGISTRY: image registry
  #  - OKTETO_BUILD_YB-DEMO-CONNECT_REPOSITORY: image repo
  #  - OKTETO_BUILD_YB-DEMO-CONNECT_IMAGE: image name
  #  - OKTETO_BUILD_YB-DEMO-CONNECT_TAG: image tag
  yb-demo-connect:
    context: .
    dockerfile: .
    image: yugabytedb/yugabyte:2.15.0.0-b11

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_YB-DEMO-INIT_REGISTRY: image registry
  #  - OKTETO_BUILD_YB-DEMO-INIT_REPOSITORY: image repo
  #  - OKTETO_BUILD_YB-DEMO-INIT_IMAGE: image name
  #  - OKTETO_BUILD_YB-DEMO-INIT_TAG: image tag
  yb-demo-init:
    context: .
    dockerfile: .
    image: yugabytedb/yugabyte:2.15.0.0-b11

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_YB-DEMO-METRICS_REGISTRY: image registry
  #  - OKTETO_BUILD_YB-DEMO-METRICS_REPOSITORY: image repo
  #  - OKTETO_BUILD_YB-DEMO-METRICS_IMAGE: image name
  #  - OKTETO_BUILD_YB-DEMO-METRICS_TAG: image tag
  yb-demo-metrics:
    context: .
    dockerfile: .
    image: yugabytedb/yugabyte:2.15.0.0-b11

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_YB-DEMO-READ_REGISTRY: image registry
  #  - OKTETO_BUILD_YB-DEMO-READ_REPOSITORY: image repo
  #  - OKTETO_BUILD_YB-DEMO-READ_IMAGE: image name
  #  - OKTETO_BUILD_YB-DEMO-READ_TAG: image tag
  yb-demo-read:
    context: .
    dockerfile: .
    image: yugabytedb/yugabyte:2.15.0.0-b11

  # You can use the following env vars to refer to this image in your deploy commands:
  #  - OKTETO_BUILD_YB-DEMO-WRITE_REGISTRY: image registry
  #  - OKTETO_BUILD_YB-DEMO-WRITE_REPOSITORY: image repo
  #  - OKTETO_BUILD_YB-DEMO-WRITE_IMAGE: image name
  #  - OKTETO_BUILD_YB-DEMO-WRITE_TAG: image tag
  yb-demo-write:
    context: .
    dockerfile: .
    image: yugabytedb/yugabyte:2.15.0.0-b11

# The deploy section defines how to deploy your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#deploy
deploy:
  compose:
    file: docker-compose.yaml

# The dependencies section defines other git repositories to be deployed as part of your development environment
# More info: https://www.okteto.com/docs/reference/manifest/#dependencies
# dependencies:
#   - https://github.com/okteto/sample


# The dev section defines how to activate a development container
# More info: https://www.okteto.com/docs/reference/manifest/#dev
dev:
  yb-demo-connect:
    image: yugabytedb/yugabyte:2.15.0.0-b11
    command:
      - bash
      - client/ybdemo.sh
      - connect
      - "9"
    sync:
      - client:/home/yugabyte/client
  yb-demo-init:
    image: yugabytedb/yugabyte:2.15.0.0-b11
    command:
      - bash
      - client/ybdemo.sh
      - init
    sync:
      - client:/home/yugabyte/client
  yb-demo-metrics:
    image: yugabytedb/yugabyte:2.15.0.0-b11
    command:
      - bash
      - client/ybdemo.sh
      - ybwr
    sync:
      - client:/home/yugabyte/client
  yb-demo-read:
    image: yugabytedb/yugabyte:2.15.0.0-b11
    command:
      - bash
      - client/ybdemo.sh
      - read
      - "1"
    sync:
      - client:/home/yugabyte/client
  yb-demo-write:
    image: yugabytedb/yugabyte:2.15.0.0-b11
    command:
      - bash
      - client/ybdemo.sh
      - insert
      - "1"
    sync:
      - client:/home/yugabyte/client

