
version: '2'

services:

# demos with connect / read / write workloads

  yb-demo-connect:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","connect","9"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-read:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","read","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-write:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","insert","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

# table create and other initialization for demos

  yb-demo-init:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","init"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-metrics:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","ybwr"]
      deploy:
          restart_policy:
             condition: on-failure

# yb-master and yb-tservers


  yb-master-0:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-master-0
      hostname: yb-master-0.az1.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud
                --placement_region=eu-west
                --placement_zone=az1
                --rpc_bind_addresses=yb-master-0.az1.eu-west.cloud:7100
                --master_addresses=yb-master-0:7100
                --replication_factor=1
                --rpc_connection_timeout_ms=15000
                "
      ports:
      - "7000:7000"


  yb-tserver-0:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-0
      hostname: yb-tserver-0.az1.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=eu-west 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-0.az1.eu-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9000:9000"
      - "5433:5433"
      depends_on:
      - yb-master-0


  yb-tserver-1:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-1
      hostname: yb-tserver-1.az1.us-east.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-east 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-1.az1.us-east.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9001:9000"
      - "5434:5433"
      depends_on:
      - yb-master-0


  yb-tserver-2:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-2
      hostname: yb-tserver-2.az1.us-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-2.az1.us-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9002:9000"
      - "5435:5433"
      depends_on:
      - yb-master-0


  yb-tserver-3:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-3
      hostname: yb-tserver-3.az2.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=eu-west 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-3.az2.eu-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9003:9000"
      - "5436:5433"
      depends_on:
      - yb-master-0


  yb-tserver-4:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-4
      hostname: yb-tserver-4.az2.us-east.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-east 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-4.az2.us-east.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9004:9000"
      - "5437:5433"
      depends_on:
      - yb-master-0


  yb-tserver-5:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-5
      hostname: yb-tserver-5.az2.us-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-5.az2.us-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9005:9000"
      - "5438:5433"
      depends_on:
      - yb-master-0


  yb-tserver-6:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-6
      hostname: yb-tserver-6.az3.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=eu-west 
                --placement_zone=az3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-6.az3.eu-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9006:9000"
      - "5439:5433"
      depends_on:
      - yb-master-0


  yb-tserver-7:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-7
      hostname: yb-tserver-7.az3.us-east.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-east 
                --placement_zone=az3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-7.az3.us-east.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9007:9000"
      - "5440:5433"
      depends_on:
      - yb-master-0


  yb-tserver-8:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-8
      hostname: yb-tserver-8.az3.us-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-8.az3.us-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9008:9000"
      - "5441:5433"
      depends_on:
      - yb-master-0


  yb-tserver-9:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-9
      hostname: yb-tserver-9.az1.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=eu-west 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-9.az1.eu-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9009:9000"
      - "5442:5433"
      depends_on:
      - yb-master-0


  yb-tserver-10:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-10
      hostname: yb-tserver-10.az1.us-east.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-east 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-10.az1.us-east.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9010:9000"
      - "5443:5433"
      depends_on:
      - yb-master-0


  yb-tserver-11:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-11
      hostname: yb-tserver-11.az1.us-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-11.az1.us-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9011:9000"
      - "5444:5433"
      depends_on:
      - yb-master-0


  yb-tserver-12:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-12
      hostname: yb-tserver-12.az2.eu-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=eu-west 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-12.az2.eu-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9012:9000"
      - "5445:5433"
      depends_on:
      - yb-master-0


  yb-tserver-13:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-13
      hostname: yb-tserver-13.az2.us-east.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-east 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-13.az2.us-east.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9013:9000"
      - "5446:5433"
      depends_on:
      - yb-master-0


  yb-tserver-14:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      container_name: yb-tserver-14
      hostname: yb-tserver-14.az2.us-west.cloud
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-14.az2.us-west.cloud:9100 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9014:9000"
      - "5447:5433"
      depends_on:
      - yb-master-0

# adding a template to add more replicas

  yb-tserver-n:
      image: yugabytedb/yugabyte:2.15.2.1-b1
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver --ysql_beta_feature_tablespace_alteration=true --ysql_enable_packed_row=true --ysql_beta_features=true --yb_enable_read_committed_isolation=true --default_memory_limit_to_ram_ratio=0.20
                --placement_cloud=cloud 
                --placement_region=us-west 
                --placement_zone=az3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --tserver_master_addrs=yb-master-0:7100 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      deploy:
          replicas: 0
      depends_on:
      - yb-master-0
