
version: '2'

services:

# demos with connect / read / write workloads

  yb-demo-connect:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","connect","9"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-read:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","read","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-write:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","insert","1"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

# table create and other initialization for demos

  yb-demo-init:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","init"]
      deploy:
          replicas: 0
          restart_policy:
             condition: on-failure

  yb-demo-metrics:
      image: yugabytedb/yugabyte:latest
      volumes:
          - ./client:/home/yugabyte/client
      command: ["bash","client/ybdemo.sh","ybwr"]
      deploy:
          restart_policy:
             condition: on-failure

# yb-master and yb-tservers


  yb-master-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-0
      hostname: yb-master-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud
                --placement_region=region
                --placement_zone=zone1
                --rpc_bind_addresses=yb-master-0:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                --rpc_connection_timeout_ms=15000
                "
      ports:
      - "7000:7000"


  yb-tserver-0:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-0
      hostname: yb-tserver-0
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone1 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-0:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9000:9000"
      - "5433:5433"
      depends_on:
      - yb-master-2


  yb-master-1:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-1
      hostname: yb-master-1
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud
                --placement_region=region
                --placement_zone=zone2
                --rpc_bind_addresses=yb-master-1:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                --rpc_connection_timeout_ms=15000
                "
      ports:
      - "7001:7000"
      depends_on:
      - yb-master-0


  yb-tserver-1:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-1
      hostname: yb-tserver-1
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone2 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-1:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9001:9000"
      - "5434:5433"
      depends_on:
      - yb-master-2


  yb-master-2:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-2
      hostname: yb-master-2
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-master 
                --fs_data_dirs=/home/yugabyte/data
                --placement_cloud=cloud
                --placement_region=region
                --placement_zone=zone3
                --rpc_bind_addresses=yb-master-2:7100
                --master_addresses=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100
                --replication_factor=3
                --rpc_connection_timeout_ms=15000
                "
      ports:
      - "7002:7000"
      depends_on:
      - yb-master-1


  yb-tserver-2:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-2
      hostname: yb-tserver-2
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --rpc_bind_addresses=yb-tserver-2:9100 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      ports:
      - "9002:9000"
      - "5435:5433"
      depends_on:
      - yb-master-2

# adding a template to add more replicas

  yb-tserver-n:
      image: yugabytedb/yugabyte:latest
      command: bash -c "
                rm -rf /tmp/.yb* ; 
                /home/yugabyte/bin/yb-tserver 
                --placement_cloud=cloud 
                --placement_region=region 
                --placement_zone=zone3 
                --enable_ysql=true 
                --fs_data_dirs=/home/yugabyte/data 
                --tserver_master_addrs=yb-master-0:7100,yb-master-1:7100,yb-master-2:7100 
                --replication_factor=3 
                --ysql_num_shards_per_tserver=2
                --rpc_connection_timeout_ms=15000
                
                "
      deploy:
          replicas: 0
      depends_on:
      - yb-master-2
