{
 "title": "YBWR",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "retention", "label": "Snapshots to keep", "query": "2,4,12,24,60" },
   {
    "name": "metrics_to_hide",
    "label": "Metrics to hide",
    "query": "create extension if not exists tablefunc;\n-- the \"ybwr_snapshots\" table stores snapshots of tserver metrics, gathered by \"ybwr_snap\", reading all endpoints known by \"yb_servers()\"\ncreate table if not exists ybwr_snapshots(host text default '', ts timestamptz default clock_timestamp(),  metrics jsonb, primary key (ts asc, host));\ncreate or replace function ybwr_snap(snaps_to_keep int default 6) returns timestamptz as $DO$\ndeclare i record; \nbegin\ndelete from ybwr_snapshots where ts not in (select distinct ts from ybwr_snapshots order by ts desc limit snaps_to_keep);\nfor i in (select host from yb_servers()) loop \n execute format(\n  $COPY$\n  copy ybwr_snapshots(host,metrics) from program\n   $BASH$\n   exec 5<>/dev/tcp/%s/9000 ; awk 'BEGIN{printf \"%s\\t\"}/[[]/{in_json=1}in_json==1{printf $0}' <&5 & printf \"GET /metrics HTTP/1.0\\r\\n\\r\\n\" >&5\n   $BASH$\n  $COPY$\n ,i.host,i.host); \nend loop; \nreturn clock_timestamp(); \nend; \n$DO$ language plpgsql;\ncreate or replace view ybwr_report as\nselect value,round(value/seconds) rate,host,tablet_id,is_raft_leader,namespace_name,table_name,metric_name,ts,relative_snap_id\nfrom (\nselect ts,host,metric_name,namespace_name,table_name\n,tablet_id,\nsum(case when metric_name='is_raft_leader' then metric_value end)\n  over(partition by host,namespace_name,table_name,tablet_id,ts)\n is_raft_leader\n,metric_value-lead(metric_value)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc) as value\n,extract(epoch from ts-lead(ts)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc)) as seconds\n,rank()over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc) as relative_snap_id\n,metric_value,metric_sum,metric_count\nfrom (\nselect host,ts\n ,jsonb_array_elements(metrics)->>'type' as type\n ,jsonb_array_elements(metrics)->>'id'   as tablet_id\n ,jsonb_array_elements(metrics)->'attributes'->>'namespace_name'  as namespace_name\n ,jsonb_array_elements(metrics)->'attributes'->>'table_name'  as table_name\n ,jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'name' as metric_name\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'value')::decimal as metric_value\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_sum')::decimal as metric_sum\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_count')::decimal as metric_count\nfrom ybwr_snapshots\n) tablets\n) tablets_delta where value>0;\n-- a convenient \"ybwr_last\" shows the last snapshot:\ncreate or replace view ybwr_last as select * from ybwr_report where relative_snap_id=1;\n-- a convenient \"ybwr_snap_and_show_tablet_load\" takes a snapshot and show the metrics\ncreate or replace view ybwr_snap_and_show_tablet_load as \nselect value,rate,namespace_name,table_name,metric_name,host,tablet_id,is_raft_leader\n,to_char(100*value/sum(value)over(partition by namespace_name,table_name,metric_name),'999%') as \"%table\"\n,sum(value)over(partition by namespace_name,table_name,metric_name) as \"table\"\nfrom ybwr_last\nwhere table_name not in ('metrics','ybwr_snapshots')\nand metric_name not in ('follower_lag_ms')\norder by ts desc,namespace_name,table_name,host,tablet_id,\"table\" desc,value desc,metric_name;\nselect distinct metric_name as \"__value\",metric_name as \"__text\" from ybwr_report,ybwr_snap($retention) order by 1;"
   },
   {
    "name": "metrics_to_hide_list",
    "query": "select case when length($$${metrics_to_hide:singlequote}$$)>0 then $$not in (${metrics_to_hide:singlequote}) $$ else ' is not null ' end"
   }
  ]
 },
 "panels": [
  {
   "title": "Snapshots",
   "type": "table",
   "description": "Takes a snapshot and display all",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select to_char(min(ts),'d yyyy-mm-dd hh24:mi') as snapshot,string_agg(distinct host,',') as hosts,(count(*)/count(distinct host)) num \nfrom ybwr_snap($retention) --> this takes a snapshot\n,ybwr_snapshots \ngroup by date_trunc('minute', ts) order by 1 desc;"
    }
   ]
  },
  {
   "title": "Show last tablet metrics",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "delete from ybwr_snapshots where not ($__timeFilter(ts));\nwith \nybwr_last as (\nselect * from ybwr_report where relative_snap_id=1\n),\nybwr_snap_and_show_tablet_load as (\nselect value,rate,namespace_name,table_name,metric_name,host,tablet_id\n,to_char(100*value/sum(value)over(partition by namespace_name,table_name,metric_name),'999%') as \"%table\"\n,sum(value)over(partition by namespace_name,table_name,metric_name) as \"table\"\nfrom ybwr_last\nwhere table_name not in ('metrics','ybwr_snapshots')\nand metric_name not in ('follower_lag_ms')\norder by ts desc,namespace_name,table_name,host,tablet_id,\"table\" desc,value desc,metric_name\n)\nselect \"rocksdb_number_db_seek\",\"rocksdb_number_db_next\",\"rocksdb_number_db_next_found\",\"rocksdb_number_db_prev\",\"rocksdb_number_db_prev_found\",row_name as \"dbname / relname / tserver / tabletid\"\nfrom crosstab($$\nselect format('%s %s %s',namespace_name,table_name,host) row_name, metric_name category, value \nfrom ybwr_snap_and_show_tablet_load \nwhere namespace_name not in ('system') and metric_name in ('rocksdb_number_db_seek','rocksdb_number_db_next','rocksdb_number_db_next_found','rocksdb_number_db_prev','rocksdb_number_db_prev_found') \norder by row_name\n$$) as (row_name text, \"rocksdb_number_db_seek\" decimal, \"rocksdb_number_db_next\" decimal, \"rocksdb_number_db_next_found\" decimal, \"rocksdb_number_db_prev\" decimal, \"rocksdb_number_db_prev_found\" decimal)"
    }
   ]
  },
  {
   "title": "yb_servers()",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select host,port,cloud,region,zone,node_type from yb_servers()"
    }
   ]
  },
  {
   "title": "All metrics in timelime ",
   "type": "timeseries",
   "description": "Filter: ${metrics_to_hide_list:raw}",
   "gridPos": { "h": 13, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\nybwr_report as (\nselect value,round(value/seconds) rate,host,tablet_id,namespace_name,table_name,metric_name,ts,relative_snap_id\nfrom (\nselect ts,host,metric_name,namespace_name,table_name,tablet_id\n,metric_value-lead(metric_value)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc) as value\n,extract(epoch from ts-lead(ts)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc)) as seconds\n,rank()over() as relative_snap_id\n,metric_value,metric_sum,metric_count\nfrom (\nselect host,ts\n ,jsonb_array_elements(metrics)->>'type' as type\n ,jsonb_array_elements(metrics)->>'id'   as tablet_id\n ,jsonb_array_elements(metrics)->'attributes'->>'namespace_name'  as namespace_name\n ,jsonb_array_elements(metrics)->'attributes'->>'table_name'  as table_name\n ,jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'name' as metric_name\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'value')::decimal as metric_value\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_sum')::decimal as metric_sum\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_count')::decimal as metric_count\nfrom ybwr_snapshots where $__timeFilter(ts)\n) tablets\n) tablets_delta where value>0\n)\nselect ts as time, metric_name, max(value) as value \nfrom ybwr_report \nwhere  metric_name  ${metrics_to_hide_list:raw}\ngroup by ts, metric_name order by ts asc, value desc\n"
    }
   ]
  },
  {
   "title": "All metrics in timelime ",
   "type": "table",
   "description": "Visible: ${metrics_to_hide}",
   "gridPos": { "h": 13, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with\nybwr_report as (\nselect value,round(value/seconds) rate,host,tablet_id,namespace_name,table_name,metric_name,ts,relative_snap_id\nfrom (\nselect ts,host,metric_name,namespace_name,table_name,tablet_id\n,metric_value-lead(metric_value)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc) as value\n,extract(epoch from ts-lead(ts)over(partition by host,namespace_name,table_name,tablet_id,metric_name order by ts desc)) as seconds\n,rank()over() as relative_snap_id\n,metric_value,metric_sum,metric_count\nfrom (\nselect host,ts\n ,jsonb_array_elements(metrics)->>'type' as type\n ,jsonb_array_elements(metrics)->>'id'   as tablet_id\n ,jsonb_array_elements(metrics)->'attributes'->>'namespace_name'  as namespace_name\n ,jsonb_array_elements(metrics)->'attributes'->>'table_name'  as table_name\n ,jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'name' as metric_name\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'value')::decimal as metric_value\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_sum')::decimal as metric_sum\n ,(jsonb_array_elements(jsonb_array_elements(metrics)->'metrics')->>'total_count')::decimal as metric_count\nfrom ybwr_snapshots where $__timeFilter(ts)\n) tablets\n) tablets_delta where value>0\n)\nselect max(value)/extract(epoch from max(ts)-min(ts)) as \"max()/second\",metric_name\n,case when metric_name  ${metrics_to_hide_list:raw} then '✔' else '❌' end \"Visible?\"\nfrom ybwr_report \n--where  metric_name  ${metrics_to_hide_list:raw}\ngroup by metric_name having max(ts)>min(ts) order by \"max()/second\" desc\n"
    }
   ]
  }
 ]
}